const questions = [
    "Apa isi UU Cipta Kerja?",
    "Apa tujuan UU Cipta Kerja?",
    "Apa isi UU ITE?",
    "Apa yang diatur dalam UU Ketenagakerjaan?",
    "Apa saja larangan dalam UU Perlindungan Konsumen?",
    "Apa isi UU No. 1 Tahun 1974 tentang Perkawinan?",
    "Apa isi UU No. 23 Tahun 2002 tentang Perlindungan Anak?",
    "Apa isi UU No. 22 Tahun 2009 tentang Lalu Lintas?",
    "Apa isi UU No. 11 Tahun 2020?",
    "Apa isi UU tentang ASN?",
    "Apa isi UU Pendidikan Nasional?",
    "Apa isi UU Sisdiknas?",
    "Apa isi UU Pemilu?",
    "Apa yang diatur dalam UU Pers?",
    "Apa isi UU tentang Kesehatan Jiwa?",
    "Apa isi UU Rumah Tangga?",
    "Apa isi UU KPK?",
    "Apa isi UU Mahkamah Konstitusi?",
    "Apa isi UU tentang Otonomi Daerah?",
    "Apa isi UU Desa?",
    "Apa isi UU tentang Minerba?",
    "Apa isi UU Cukai?",
    "Apa isi UU Perpajakan?",
    "Apa isi UU tentang Lingkungan Hidup?",
    "Apa isi UU Kehutanan?",
    "Apa isi UU Perikanan?",
    "Apa isi UU Pangan?",
    "Apa isi UU Energi?",
    "Apa isi UU tentang Penanggulangan Bencana?",
    "Apa isi UU Anti Korupsi?",
    "Apa isi UU Terorisme?",
    "Apa isi UU No. 5 Tahun 2014 tentang ASN?",
    "Apa isi UU No. 20 Tahun 2003?",
    "Apa isi UU No. 6 Tahun 2014 tentang Desa?",
    "Apa isi UU No. 25 Tahun 2009 tentang Pelayanan Publik?",
    "Apa isi UU No. 36 Tahun 2009 tentang Kesehatan?",
    "Apa isi UU No. 24 Tahun 2007 tentang Bencana?",
    "Apa isi UU No. 14 Tahun 2008 tentang Keterbukaan Informasi Publik?",
    "Apa isi UU No. 13 Tahun 2003 tentang Ketenagakerjaan?",
    "Apa isi Perpres Nomor 10 Tahun 2021?",
    "Apa isi PP Nomor 35 Tahun 2021?",
    "Apa isi UU tentang Stunting?",
    "Apa isi Perpres tentang Pencegahan Korupsi?",
    "Apa isi Perda tentang Sampah?",
    "Apa isi Perda tentang Pajak Daerah?",
    "Apa isi Perda tentang IMB?",
    "Apa isi Perda tentang Ketertiban Umum?",
    "Apa isi UU tentang Ibu Kota Negara?",
    "Apa isi UU tentang Perlindungan Data Pribadi?",
    "Apa isi UU Nomor 19 Tahun 2016?",
    "Apa isi revisi UU ITE?",
    "Apa isi Perpres tentang Energi Terbarukan?",
    "Apa isi Perpres tentang Kesehatan Ibu dan Anak?",
    "Apa isi Permendikbud tentang Kurikulum Merdeka?",
    "Apa isi Permenaker tentang Upah Minimum?",
    "Apa isi Permenkes tentang Stunting?",
    "Apa isi Peraturan Pemerintah tentang Cuti Bersalin?",
    "Apa isi UU tentang Tindak Pidana Korupsi?",
    "Apa isi UU tentang Informasi Publik?",
    "Apa isi UU tentang Hak Cipta?",
    "Apa isi UU tentang Paten?",
    "Apa isi UU tentang Merek Dagang?",
    "Apa isi UU tentang Perdagangan?",
    "Apa isi UU tentang Pengadaan Barang dan Jasa?",
    "Apa isi UU tentang Kesejahteraan Sosial?",
    "Apa isi UU tentang Disabilitas?",
    "Apa isi UU tentang Pekerja Migran?",
    "Apa isi UU tentang Perbankan?",
    "Apa isi UU tentang Keuangan Negara?",
    "Apa isi UU tentang OJK?",
    "Apa isi UU tentang Bank Indonesia?",
    "Apa isi UU tentang Pendidikan Tinggi?",
    "Apa isi UU tentang Kebudayaan?",
    "Apa isi UU tentang Perfilman?",
    "Apa isi UU tentang Teknologi Informasi?",
    "Apa isi UU tentang Transaksi Elektronik?",
    "Apa isi UU tentang Layanan Digital?",
    "Apa isi Peraturan Pemerintah tentang Pendidikan Inklusif?",
    "Apa isi Peraturan Menteri Agama tentang Pernikahan?",
    "Apa isi UU tentang Imigrasi?",
    "Apa isi UU tentang Warga Negara Asing?",
    "Apa isi UU tentang Kependudukan?",
    "Apa isi UU tentang Pemuda?",
    "Apa isi UU tentang Olahraga?",
    "Apa isi UU tentang Perpustakaan?",
    "Apa isi UU tentang Kearsipan?",
    "Apa isi UU tentang Statistik?",
    "Apa isi UU tentang Telekomunikasi?",
    "Apa isi UU tentang Penyiaran?",
    "Apa isi UU tentang Persaingan Usaha?",
    "Apa isi UU tentang Perindustrian?",
    "Apa isi UU tentang Koperasi?",
    "Apa isi UU tentang Usaha Mikro?",
    "Apa isi UU tentang UMKM?",
    "Apa isi Perpres tentang Ekonomi Kreatif?",
    "Apa isi UU tentang Pelayanan Kesehatan?",
    "Apa isi UU tentang BPJS?",
    "Apa isi UU tentang Pendidikan Anak Usia Dini?",
    "Apa isi UU tentang Perdagangan Internasional?",
    "Apa isi UU tentang Bea Cukai?",
    "Apa isi UU tentang Kepolisian?",
    "Apa isi UU tentang TNI?",
    "Apa isi UU tentang Lalu Lintas?",
    "Apa isi UU tentang Pajak Penghasilan?",
    "Apa isi UU tentang Pajak Daerah?"
]

const getRandomQuestions = (questions: string[], count: number) => {
    const shuffled = questions.sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
}

export const randomQuestions = getRandomQuestions(questions, 4);